{
  "uid" : "d612e397411e7d18",
  "name" : "\"before all\" hook: deploy implementation for \"upgrade a proxy by upgrading its beacon\"",
  "fullName" : "Contract: BeaconProxy.\"before all\" hook: deploy implementation for \"upgrade a proxy by upgrading its beacon\"",
  "historyId" : "ce8e990931270c9056c1c718816c98d0",
  "time" : {
    "start" : 1635554971846,
    "stop" : 1635554971846,
    "duration" : 0
  },
  "description" : "",
  "descriptionHtml" : "",
  "status" : "broken",
  "statusMessage" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a28660a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
  "statusTrace" : "Error: Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a28660a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))\n                    at Context.<anonymous> (test/proxy/beacon/BeaconProxy.test.js:49:58)",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "suite",
    "value" : "Contract: BeaconProxy"
  }, {
    "name" : "testClass",
    "value" : "Contract: BeaconProxy"
  }, {
    "name" : "testMethod",
    "value" : "\"before all\" hook: deploy implementation for \"upgrade a proxy by upgrading its beacon\""
  }, {
    "name" : "package",
    "value" : "Contract: BeaconProxy"
  }, {
    "name" : "resultFormat",
    "value" : "allure1"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "17c0ab5dcb6375c1",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a17de5e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635554902472,
        "stop" : 1635554902472,
        "duration" : 0
      }
    }, {
      "uid" : "e7480b7451be3685",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f238bfd3c10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635554901566,
        "stop" : 1635554901566,
        "duration" : 0
      }
    }, {
      "uid" : "bb315ab7d1ad2f8d",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a066cd30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635554890666,
        "stop" : 1635554890666,
        "duration" : 0
      }
    }, {
      "uid" : "8b5735fce5dbfe6e",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a07f43a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635554886120,
        "stop" : 1635554886120,
        "duration" : 0
      }
    }, {
      "uid" : "4ef724a3542eb2cd",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a042db80>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635554836608,
        "stop" : 1635554836608,
        "duration" : 0
      }
    }, {
      "uid" : "b94f57a28d0b2971",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a0677a90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635554821122,
        "stop" : 1635554821122,
        "duration" : 0
      }
    }, {
      "uid" : "9683084c407eb7b0",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a0fe6c70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635554808359,
        "stop" : 1635554808359,
        "duration" : 0
      }
    }, {
      "uid" : "2afa095bae77be67",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f238be7e550>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635554805867,
        "stop" : 1635554805867,
        "duration" : 0
      }
    } ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 2,
        "skipped" : 0,
        "passed" : 0,
        "unknown" : 0,
        "total" : 2
      },
      "items" : [ {
        "uid" : "9afade0b3785bdcb",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/6//#testresult/9afade0b3785bdcb",
        "status" : "broken",
        "statusDetails" : "HH110: Invalid JSON-RPC response received: <html>\n                <head><title>502 Bad Gateway</title></head>\n                <body>\n                <center><h1>502 Bad Gateway</h1></center>\n                <hr><center>nginx/1.18.0 (Ubuntu)</center>\n                </body>\n                </html>\n                ",
        "time" : {
          "start" : 1635551253189,
          "stop" : 1635551253189,
          "duration" : 0
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "d612e397411e7d18.json",
  "parameterValues" : [ ]
}