{
  "uid" : "3bbc2e0f0bd08690",
  "name" : "is correctly detected in first argument position",
  "fullName" : "Contract: Math max.is correctly detected in first argument position",
  "historyId" : "f103c420f724dd28ba8e67ecf484f3d3",
  "time" : {
    "start" : 1635782665408,
    "stop" : 1635782665967,
    "duration" : 559
  },
  "description" : "",
  "descriptionHtml" : "",
  "status" : "broken",
  "statusMessage" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a0fb4ee0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
  "statusTrace" : "Error: Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a0fb4ee0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))\n                    at Context.<anonymous> (test/utils/math/Math.test.js:12:35)\n                    at processImmediate (node:internal/timers:464:21)",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "suite",
    "value" : "Contract: Math max"
  }, {
    "name" : "testClass",
    "value" : "Contract: Math max"
  }, {
    "name" : "testMethod",
    "value" : "is correctly detected in first argument position"
  }, {
    "name" : "package",
    "value" : "Contract: Math max"
  }, {
    "name" : "resultFormat",
    "value" : "allure1"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "3bbc2e0f0bd08690.json",
  "parameterValues" : [ ]
}