{
  "uid" : "3f8f8ab2fa4f577",
  "name" : "unset",
  "fullName" : "Contract: TimersBlockNumber.unset",
  "historyId" : "b5b2e2fd263f75fdffd0b991fc3006b0",
  "time" : {
    "start" : 1635782778607,
    "stop" : 1635782779592,
    "duration" : 985
  },
  "description" : "",
  "descriptionHtml" : "",
  "status" : "broken",
  "statusMessage" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a0420400>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
  "statusTrace" : "Error: Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a0420400>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))\n                    at Context.<anonymous> (test/utils/TimersBlockNumberImpl.test.js:8:52)\n                    at processImmediate (node:internal/timers:464:21)",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "suite",
    "value" : "Contract: TimersBlockNumber"
  }, {
    "name" : "testClass",
    "value" : "Contract: TimersBlockNumber"
  }, {
    "name" : "testMethod",
    "value" : "unset"
  }, {
    "name" : "package",
    "value" : "Contract: TimersBlockNumber"
  }, {
    "name" : "resultFormat",
    "value" : "allure1"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "a86a2d58ca481d56",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a04180a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782712625,
        "stop" : 1635782713186,
        "duration" : 561
      }
    }, {
      "uid" : "f64367727ceed310",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a0689c10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782673889,
        "stop" : 1635782674452,
        "duration" : 563
      }
    }, {
      "uid" : "4d7d770032f0507b",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a0436fd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782664708,
        "stop" : 1635782665270,
        "duration" : 562
      }
    }, {
      "uid" : "1127111fe6d07305",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a0433e50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782645179,
        "stop" : 1635782646480,
        "duration" : 1301
      }
    }, {
      "uid" : "5ceac00068929089",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a07ca790>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782622972,
        "stop" : 1635782623535,
        "duration" : 563
      }
    }, {
      "uid" : "23a04cfb5a4cee4e",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a04201c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782557610,
        "stop" : 1635782558172,
        "duration" : 562
      }
    }, {
      "uid" : "62eef36dcec09b",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a044c0a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782557400,
        "stop" : 1635782557963,
        "duration" : 563
      }
    }, {
      "uid" : "8413c091f23b8d8e",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a063d550>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782557055,
        "stop" : 1635782557616,
        "duration" : 561
      }
    } ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 4,
        "skipped" : 0,
        "passed" : 0,
        "unknown" : 0,
        "total" : 4
      },
      "items" : [ {
        "uid" : "bb114fadaf314035",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/8//#testresult/bb114fadaf314035",
        "status" : "broken",
        "statusDetails" : "Returned error: Transaction simulation failed: Error processing Instruction 0: invalid account data for instruction",
        "time" : {
          "start" : 1635590860828,
          "stop" : 1635590872945,
          "duration" : 12117
        }
      }, {
        "uid" : "8b881704816803fb",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/7//#testresult/8b881704816803fb",
        "status" : "broken",
        "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a07c3670>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
        "time" : {
          "start" : 1635555058416,
          "stop" : 1635555059388,
          "duration" : 972
        }
      }, {
        "uid" : "bd243eab1eccfba3",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/6//#testresult/bd243eab1eccfba3",
        "status" : "broken",
        "statusDetails" : "HH110: Invalid JSON-RPC response received: <html>\n                <head><title>502 Bad Gateway</title></head>\n                <body>\n                <center><h1>502 Bad Gateway</h1></center>\n                <hr><center>nginx/1.18.0 (Ubuntu)</center>\n                </body>\n                </html>\n                ",
        "time" : {
          "start" : 1635551287736,
          "stop" : 1635551293959,
          "duration" : 6223
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "3f8f8ab2fa4f577.json",
  "parameterValues" : [ ]
}