{
  "uid" : "64acad95e7a29d23",
  "name" : "returns the transaction sender when called from an EOA",
  "fullName" : "Contract: Context msgSender.returns the transaction sender when called from an EOA",
  "historyId" : "a21577e26a37035be90b52e61eb3e09",
  "time" : {
    "start" : 1635782612785,
    "stop" : 1635782613757,
    "duration" : 972
  },
  "description" : "",
  "descriptionHtml" : "",
  "status" : "broken",
  "statusMessage" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a0680c40>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
  "statusTrace" : "Error: Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a0680c40>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))\n                    at Context.<anonymous> (test/utils/Context.test.js:12:41)\n                    at processImmediate (node:internal/timers:464:21)",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "suite",
    "value" : "Contract: Context msgSender"
  }, {
    "name" : "testClass",
    "value" : "Contract: Context msgSender"
  }, {
    "name" : "testMethod",
    "value" : "returns the transaction sender when called from an EOA"
  }, {
    "name" : "package",
    "value" : "Contract: Context msgSender"
  }, {
    "name" : "resultFormat",
    "value" : "allure1"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "64acad95e7a29d23.json",
  "parameterValues" : [ ]
}