{
  "uid" : "65d4d6a51dd0a9fb",
  "name" : "batches function calls",
  "fullName" : "Contract: MulticallToken.batches function calls",
  "historyId" : "6c98da7981df0b1e9891e7c04076e848",
  "time" : {
    "start" : 1635782770841,
    "stop" : 1635782771804,
    "duration" : 963
  },
  "description" : "",
  "descriptionHtml" : "",
  "status" : "broken",
  "statusMessage" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a0420c40>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
  "statusTrace" : "Error: Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a0420c40>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))\n                    at Context.<anonymous> (test/utils/Multicall.test.js:9:55)\n                    at processImmediate (node:internal/timers:464:21)",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "suite",
    "value" : "Contract: MulticallToken"
  }, {
    "name" : "testClass",
    "value" : "Contract: MulticallToken"
  }, {
    "name" : "testMethod",
    "value" : "batches function calls"
  }, {
    "name" : "package",
    "value" : "Contract: MulticallToken"
  }, {
    "name" : "resultFormat",
    "value" : "allure1"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "980bf820116b6d5c",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a0689970>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782704482,
        "stop" : 1635782705045,
        "duration" : 563
      }
    }, {
      "uid" : "701dcf5246436d60",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a0436520>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782669367,
        "stop" : 1635782669927,
        "duration" : 560
      }
    }, {
      "uid" : "3ae2b5101ab14f53",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a067b190>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782658303,
        "stop" : 1635782658866,
        "duration" : 563
      }
    }, {
      "uid" : "1b7780cafc9a9508",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a2875100>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782634915,
        "stop" : 1635782635882,
        "duration" : 967
      }
    }, {
      "uid" : "d5f09e7333fefdd4",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a17aab80>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782616471,
        "stop" : 1635782617029,
        "duration" : 558
      }
    }, {
      "uid" : "ef44030e14f51714",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f238be7a5e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782552455,
        "stop" : 1635782553042,
        "duration" : 587
      }
    }, {
      "uid" : "62d1f2549dffd18e",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a07fcdf0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782552449,
        "stop" : 1635782553010,
        "duration" : 561
      }
    }, {
      "uid" : "5d73f04d5012f2b2",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a0428310>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782550699,
        "stop" : 1635782551256,
        "duration" : 557
      }
    } ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 4,
        "skipped" : 0,
        "passed" : 0,
        "unknown" : 0,
        "total" : 4
      },
      "items" : [ {
        "uid" : "135de0950222848a",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/8//#testresult/135de0950222848a",
        "status" : "broken",
        "statusDetails" : "Returned error: Transaction simulation failed: Error processing Instruction 0: invalid account data for instruction",
        "time" : {
          "start" : 1635590761246,
          "stop" : 1635590780767,
          "duration" : 19521
        }
      }, {
        "uid" : "e3004932d128893",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/7//#testresult/e3004932d128893",
        "status" : "broken",
        "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a07c3ca0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
        "time" : {
          "start" : 1635555050474,
          "stop" : 1635555051472,
          "duration" : 998
        }
      }, {
        "uid" : "47983d4fb8b05113",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/6//#testresult/47983d4fb8b05113",
        "status" : "broken",
        "statusDetails" : "HH110: Invalid JSON-RPC response received: <html>\n                <head><title>502 Bad Gateway</title></head>\n                <body>\n                <center><h1>502 Bad Gateway</h1></center>\n                <hr><center>nginx/1.18.0 (Ubuntu)</center>\n                </body>\n                </html>\n                ",
        "time" : {
          "start" : 1635551258443,
          "stop" : 1635551258516,
          "duration" : 73
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "65d4d6a51dd0a9fb.json",
  "parameterValues" : [ ]
}