{
  "uid" : "a7be1e16aa3b9db8",
  "name" : "reverts when trying to safeTransferFrom from holder",
  "fullName" : "Contract: ERC1155Pausable when token is paused.reverts when trying to safeTransferFrom from holder",
  "historyId" : "b42e4c5dbac481f4f1526518c5a6f1f7",
  "time" : {
    "start" : 1635782713450,
    "stop" : 1635782714430,
    "duration" : 980
  },
  "description" : "",
  "descriptionHtml" : "",
  "status" : "broken",
  "statusMessage" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f238be8c4c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
  "statusTrace" : "Error: Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f238be8c4c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))\n                    at Context.<anonymous> (test/token/ERC1155/extensions/ERC1155Pausable.test.js:13:47)\n                    at processImmediate (node:internal/timers:464:21)",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "suite",
    "value" : "Contract: ERC1155Pausable when token is paused"
  }, {
    "name" : "testClass",
    "value" : "Contract: ERC1155Pausable when token is paused"
  }, {
    "name" : "testMethod",
    "value" : "reverts when trying to safeTransferFrom from holder"
  }, {
    "name" : "package",
    "value" : "Contract: ERC1155Pausable when token is paused"
  }, {
    "name" : "resultFormat",
    "value" : "allure1"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "b9c0227ab7a63fb0",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a0683f70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782599548,
        "stop" : 1635782600113,
        "duration" : 565
      }
    }, {
      "uid" : "98729d77cad92a68",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a183cd60>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782597865,
        "stop" : 1635782598423,
        "duration" : 558
      }
    }, {
      "uid" : "77950cea84358367",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a0683160>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782597431,
        "stop" : 1635782597990,
        "duration" : 559
      }
    }, {
      "uid" : "ea197fa4cbaff977",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a183ce20>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782571437,
        "stop" : 1635782572036,
        "duration" : 599
      }
    }, {
      "uid" : "de5f517df4558a73",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a067c070>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782565030,
        "stop" : 1635782565990,
        "duration" : 960
      }
    }, {
      "uid" : "5337b095e89d27d0",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a0fe6430>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782519046,
        "stop" : 1635782519607,
        "duration" : 561
      }
    }, {
      "uid" : "fa30d30745d3810f",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a04289d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782507151,
        "stop" : 1635782507716,
        "duration" : 565
      }
    }, {
      "uid" : "f43b2e7aaef94686",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a07c3fd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782504715,
        "stop" : 1635782505273,
        "duration" : 558
      }
    } ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 4,
        "skipped" : 0,
        "passed" : 0,
        "unknown" : 0,
        "total" : 4
      },
      "items" : [ {
        "uid" : "14ed2fdd74a14a9d",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/8//#testresult/14ed2fdd74a14a9d",
        "status" : "broken",
        "statusDetails" : "Returned error: Transaction simulation failed: Error processing Instruction 0: invalid account data for instruction",
        "time" : {
          "start" : 1635590080203,
          "stop" : 1635590096834,
          "duration" : 16631
        }
      }, {
        "uid" : "16304b4d5e15af9d",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/7//#testresult/16304b4d5e15af9d",
        "status" : "broken",
        "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a0680370>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
        "time" : {
          "start" : 1635554987403,
          "stop" : 1635554988404,
          "duration" : 1001
        }
      }, {
        "uid" : "60f8f7b01584c5ba",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/6//#testresult/60f8f7b01584c5ba",
        "status" : "broken",
        "statusDetails" : "HH110: Invalid JSON-RPC response received: <html>\n                <head><title>502 Bad Gateway</title></head>\n                <body>\n                <center><h1>502 Bad Gateway</h1></center>\n                <hr><center>nginx/1.18.0 (Ubuntu)</center>\n                </body>\n                </html>\n                ",
        "time" : {
          "start" : 1635551254302,
          "stop" : 1635551254378,
          "duration" : 76
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "a7be1e16aa3b9db8.json",
  "parameterValues" : [ ]
}