{
  "uid" : "b7da4d828777b383",
  "name" : "can accept a single deposit",
  "fullName" : "Contract: ConditionalEscrow when withdrawal is allowed as an escrow deposits.can accept a single deposit",
  "historyId" : "4750b370a995fbef6fd1d5e2210878df",
  "time" : {
    "start" : 1635782759610,
    "stop" : 1635782760579,
    "duration" : 969
  },
  "description" : "",
  "descriptionHtml" : "",
  "status" : "broken",
  "statusMessage" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a17de430>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
  "statusTrace" : "Error: Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a17de430>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))\n                    at Context.<anonymous> (test/utils/escrow/ConditionalEscrow.test.js:10:50)\n                    at processImmediate (node:internal/timers:464:21)",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "suite",
    "value" : "Contract: ConditionalEscrow when withdrawal is allowed as an escrow deposits"
  }, {
    "name" : "testClass",
    "value" : "Contract: ConditionalEscrow when withdrawal is allowed as an escrow deposits"
  }, {
    "name" : "testMethod",
    "value" : "can accept a single deposit"
  }, {
    "name" : "package",
    "value" : "Contract: ConditionalEscrow when withdrawal is allowed as an escrow deposits"
  }, {
    "name" : "resultFormat",
    "value" : "allure1"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "b5bee5e23d276491",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a0436730>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782654609,
        "stop" : 1635782655194,
        "duration" : 585
      }
    }, {
      "uid" : "80ab7ee3f176508c",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a0436550>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782650183,
        "stop" : 1635782650745,
        "duration" : 562
      }
    }, {
      "uid" : "bd1cd866b5e57a80",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a0fe67f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782636557,
        "stop" : 1635782637124,
        "duration" : 567
      }
    }, {
      "uid" : "ed2d40306bbe84f3",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a28661c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782620888,
        "stop" : 1635782621856,
        "duration" : 968
      }
    }, {
      "uid" : "e87942d142c502ee",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a04202e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782600958,
        "stop" : 1635782601521,
        "duration" : 563
      }
    }, {
      "uid" : "4240e7e2b9a02807",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a0428760>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782545812,
        "stop" : 1635782546372,
        "duration" : 560
      }
    }, {
      "uid" : "83aaa84e299cf53b",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f238be8c340>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782544130,
        "stop" : 1635782544692,
        "duration" : 562
      }
    }, {
      "uid" : "a36c1830b3bee812",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a067cd00>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782534729,
        "stop" : 1635782535704,
        "duration" : 975
      }
    } ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 4,
        "skipped" : 0,
        "passed" : 0,
        "unknown" : 0,
        "total" : 4
      },
      "items" : [ {
        "uid" : "3fcc3de4ba536568",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/8//#testresult/3fcc3de4ba536568",
        "status" : "broken",
        "statusDetails" : "Returned error: Transaction simulation failed: Error processing Instruction 0: invalid account data for instruction",
        "time" : {
          "start" : 1635590629129,
          "stop" : 1635590640344,
          "duration" : 11215
        }
      }, {
        "uid" : "ac13754e6ec853e",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/7//#testresult/ac13754e6ec853e",
        "status" : "broken",
        "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a0436a60>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
        "time" : {
          "start" : 1635555038939,
          "stop" : 1635555039927,
          "duration" : 988
        }
      }, {
        "uid" : "99d260c5e54a526",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/6//#testresult/99d260c5e54a526",
        "status" : "broken",
        "statusDetails" : "HH110: Invalid JSON-RPC response received: <html>\n                <head><title>502 Bad Gateway</title></head>\n                <body>\n                <center><h1>502 Bad Gateway</h1></center>\n                <hr><center>nginx/1.18.0 (Ubuntu)</center>\n                </body>\n                </html>\n                ",
        "time" : {
          "start" : 1635551257560,
          "stop" : 1635551257622,
          "duration" : 62
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "b7da4d828777b383.json",
  "parameterValues" : [ ]
}