{
  "uid" : "d921ec25d550b754",
  "name" : "holder can burn their tokens",
  "fullName" : "Contract: ERC1155Burnable burn.holder can burn their tokens",
  "historyId" : "2097cdb0d801455d08c92f087c4dc692",
  "time" : {
    "start" : 1635782712270,
    "stop" : 1635782713239,
    "duration" : 969
  },
  "description" : "",
  "descriptionHtml" : "",
  "status" : "broken",
  "statusMessage" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a17de970>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
  "statusTrace" : "Error: Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a17de970>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))\n                    at Context.<anonymous> (test/token/ERC1155/extensions/ERC1155Burnable.test.js:16:47)\n                    at processImmediate (node:internal/timers:464:21)",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "suite",
    "value" : "Contract: ERC1155Burnable burn"
  }, {
    "name" : "testClass",
    "value" : "Contract: ERC1155Burnable burn"
  }, {
    "name" : "testMethod",
    "value" : "holder can burn their tokens"
  }, {
    "name" : "package",
    "value" : "Contract: ERC1155Burnable burn"
  }, {
    "name" : "resultFormat",
    "value" : "allure1"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "3e344260a588c91f",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a183ce20>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782598982,
        "stop" : 1635782599543,
        "duration" : 561
      }
    }, {
      "uid" : "e61a4bd7aace10f1",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a183c9d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782597302,
        "stop" : 1635782597861,
        "duration" : 559
      }
    }, {
      "uid" : "f37f2bf3d07f7df9",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a04277f0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782596871,
        "stop" : 1635782597427,
        "duration" : 556
      }
    }, {
      "uid" : "3a01e50abd462bd8",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a0420b20>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782570868,
        "stop" : 1635782571432,
        "duration" : 564
      }
    }, {
      "uid" : "26bc8ff2f711c494",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a063d370>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782563823,
        "stop" : 1635782564776,
        "duration" : 953
      }
    }, {
      "uid" : "e64aad37ed1233d5",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a0fe68e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782518481,
        "stop" : 1635782519043,
        "duration" : 562
      }
    }, {
      "uid" : "1ad2587336d0751d",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a06806a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782506585,
        "stop" : 1635782507147,
        "duration" : 562
      }
    }, {
      "uid" : "d2093d5eeca1318c",
      "status" : "broken",
      "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a0428f40>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
      "time" : {
        "start" : 1635782504150,
        "stop" : 1635782504711,
        "duration" : 561
      }
    } ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 4,
        "skipped" : 0,
        "passed" : 0,
        "unknown" : 0,
        "total" : 4
      },
      "items" : [ {
        "uid" : "39ac573cd15c11cd",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/8//#testresult/39ac573cd15c11cd",
        "status" : "broken",
        "statusDetails" : "Returned error: Transaction simulation failed: Error processing Instruction 0: invalid account data for instruction",
        "time" : {
          "start" : 1635590060432,
          "stop" : 1635590080199,
          "duration" : 19767
        }
      }, {
        "uid" : "9572b2944082ec4a",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/7//#testresult/9572b2944082ec4a",
        "status" : "broken",
        "statusDetails" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a183ce20>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
        "time" : {
          "start" : 1635554986422,
          "stop" : 1635554987397,
          "duration" : 975
        }
      }, {
        "uid" : "85ac3226f48107c2",
        "reportUrl" : "https://neonlabsorg.github.io/neon-compatibility/6//#testresult/85ac3226f48107c2",
        "status" : "broken",
        "statusDetails" : "HH110: Invalid JSON-RPC response received: <html>\n                <head><title>502 Bad Gateway</title></head>\n                <body>\n                <center><h1>502 Bad Gateway</h1></center>\n                <hr><center>nginx/1.18.0 (Ubuntu)</center>\n                </body>\n                </html>\n                ",
        "time" : {
          "start" : 1635551254234,
          "stop" : 1635551254298,
          "duration" : 64
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "d921ec25d550b754.json",
  "parameterValues" : [ ]
}