{
  "uid" : "f090f2afdb88843e",
  "name" : "adds correctly",
  "fullName" : "Contract: SafeMath with flag add.adds correctly",
  "historyId" : "155a86bfebae378b2422b633ca6c7a25",
  "time" : {
    "start" : 1635782551290,
    "stop" : 1635782551850,
    "duration" : 560
  },
  "description" : "",
  "descriptionHtml" : "",
  "status" : "broken",
  "statusMessage" : "Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a067ef40>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))",
  "statusTrace" : "Error: Returned error: HTTPConnectionPool(host='solana', port=8899): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f23a067ef40>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))\n                    at Context.<anonymous> (test/utils/math/SafeMath.test.js:20:43)\n                    at processImmediate (node:internal/timers:464:21)",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "suite",
    "value" : "Contract: SafeMath with flag add"
  }, {
    "name" : "testClass",
    "value" : "Contract: SafeMath with flag add"
  }, {
    "name" : "testMethod",
    "value" : "adds correctly"
  }, {
    "name" : "package",
    "value" : "Contract: SafeMath with flag add"
  }, {
    "name" : "resultFormat",
    "value" : "allure1"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "f090f2afdb88843e.json",
  "parameterValues" : [ ]
}